#!/usr/bin/env bash
# validate-coturn.sh — provision a destroy-after coturn for v0.1.2.x §4.4 validation.
#
# Run on a fresh Debian/Ubuntu droplet (DO, Linode, Vultr, Hetzner, ...) as root:
#
#   # AWS/GCP topology (public IP NAT'd to private NIC IP — two distinct
#   # routable IPs already), no env var needed:
#   ssh root@<vm-ip> 'bash -s' < scripts/validate-coturn.sh
#
#   # Single-public-IP providers (DO basic droplet, Linode Nanode, Hetzner
#   # single-IP) — attach a second routable IP first (DO Reserved IP /
#   # Linode Extra IP / Hetzner Floating IP), then pass via env var:
#   ssh root@<vm-ip> "SECOND_IP=<reserved-ip> bash -s" < scripts/validate-coturn.sh
#
# What it does:
#   1. apt-installs coturn (4.x)
#   2. detects the VM's public + private NIC IPs; if SECOND_IP is set, aliases
#      it to the NIC and uses the multi-IP conf form
#   3. writes /etc/turnserver.conf (two listening-ip + two external-ip pairs +
#      rfc5780 directive)
#   4. opens UDP 3478/3479 in ufw (allowing OpenSSH first so you don't lock out)
#   5. starts coturn in a tmux session, logs to /var/log/coturn-natcheck.log
#   6. greps the log for the two specific WARNING/INFO lines that signal a
#      misconfigured §4.4 path; exits non-zero if either is present
#   7. prints the natcheck command to run from your laptop
#
# When done capturing samples: `poweroff` is NOT enough — destroy the VM
# from the cloud dashboard. Hourly billing continues until destroy.

set -euo pipefail

LOG_FILE=/var/log/coturn-natcheck.log
CONF_FILE=/etc/turnserver.conf
TMUX_SESSION=coturn

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: must run as root (try: sudo bash $0)" >&2
    exit 1
fi

echo "==> Detecting public IPv4..."
# -4 forces IPv4 — on a dual-stack droplet (DO with IPv6 enabled, etc.) curl
# would otherwise prefer IPv6 and we'd get a v6 address that doesn't pair
# with the v4 NIC IP for coturn's external-ip directive.
PUBLIC_IP=$(curl -4 -fsS --max-time 5 https://ifconfig.me 2>/dev/null \
    || curl -4 -fsS --max-time 5 https://api.ipify.org 2>/dev/null \
    || true)
if [[ -z "$PUBLIC_IP" ]]; then
    echo "ERROR: could not detect public IP from ifconfig.me or api.ipify.org" >&2
    exit 1
fi

echo "==> Detecting private (NIC) IP..."
PRIVATE_NIC=$(ip route get 1.1.1.1 2>/dev/null | awk '/dev/ {for(i=1;i<=NF;i++) if($i=="dev") print $(i+1); exit}')
if [[ -z "$PRIVATE_NIC" ]]; then
    echo "ERROR: could not detect default-route NIC" >&2
    exit 1
fi
PRIVATE_IP=$(ip -4 addr show "$PRIVATE_NIC" | awk '/inet / {split($2,a,"/"); print a[1]; exit}')
if [[ -z "$PRIVATE_IP" ]]; then
    echo "ERROR: could not detect IP on NIC $PRIVATE_NIC" >&2
    exit 1
fi

echo "    PUBLIC_IP=$PUBLIC_IP"
echo "    PRIVATE_IP=$PRIVATE_IP (on $PRIVATE_NIC)"

# coturn requires TWO distinct routable IPs (see docs/coturn-setup.md).
# Topology branches:
#   AWS/GCP/Azure: PUBLIC_IP and PRIVATE_IP differ — use both directly.
#   Single-public-IP providers (DO basic, Linode Nanode, Hetzner single-IP):
#     they're equal, and there is no second routable IP available natively.
#     Caller must attach a second IP and pass it via SECOND_IP env var; the
#     script then aliases it to the NIC and writes the multi-IP conf form.
if [[ -n "${SECOND_IP:-}" ]]; then
    echo "    SECOND_IP=$SECOND_IP (from env — multi-IP form)"
    if ! ip -4 addr show "$PRIVATE_NIC" | grep -q "$SECOND_IP/"; then
        echo "==> Aliasing SECOND_IP $SECOND_IP onto $PRIVATE_NIC..."
        ip addr add "$SECOND_IP/32" dev "$PRIVATE_NIC"
    fi
    FIRST_LINE="$PUBLIC_IP"
    SECOND_LINE="$SECOND_IP"
elif [[ "$PUBLIC_IP" != "$PRIVATE_IP" ]]; then
    echo "    (AWS/GCP-style topology — public ≠ private, using both as the two distinct IPs)"
    FIRST_LINE="$PUBLIC_IP"
    SECOND_LINE="$PRIVATE_IP"
else
    echo "    (Single-public-IP VM — no SECOND_IP env var. coturn needs two distinct"
    echo "     routable IPs; this conf will fail verification. Re-run with"
    echo "     SECOND_IP=<reserved-or-floating-ip> to enable §4.4 — see docs/coturn-setup.md.)"
    FIRST_LINE="$PUBLIC_IP"
    SECOND_LINE="$PUBLIC_IP"
fi
echo

echo "==> Installing coturn + tmux..."
DEBIAN_FRONTEND=noninteractive apt-get update -qq
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq coturn tmux >/dev/null
echo "    coturn $(turnserver -h 2>&1 | head -1 | awk '{print $NF}') installed"

echo "==> Writing $CONF_FILE..."
cat > "$CONF_FILE" <<EOF
# Generated by validate-coturn.sh for natcheck §4.4 validation.
# Diagnostic-test posture: no auth, no TLS, no DTLS. NOT a production STUN
# service. Destroy the VM after capturing samples.

listening-port=3478
alt-listening-port=3479
listening-ip=$FIRST_LINE
listening-ip=$SECOND_LINE
external-ip=$FIRST_LINE/$FIRST_LINE
external-ip=$SECOND_LINE/$SECOND_LINE

# Required on coturn 4.10+ (RFC 5780 default flipped to OFF). Cosmetic
# "Bad configuration format" warning on 4.5/4.6 — harmless, kept for
# forward compat.
rfc5780

no-auth
no-tls
no-dtls

# log-file=stdout: explicit directive needed because coturn 4.5/4.6 detects
# non-TTY stdout (the tee pipe) and otherwise writes only to PID-named files
# (/var/log/turn_<pid>_<date>.log) — the bare path we grep stays empty and
# the script reports a false-positive "OK". With log-file=stdout, coturn
# emits to standard output, tee captures to LOG_FILE as a flat file.
log-file=stdout
verbose
EOF

# Disable Debian's stock coturn systemd unit so it doesn't fight our tmux'd
# instance for ports 3478/3479. Idempotent.
if systemctl is-active --quiet coturn 2>/dev/null; then
    echo "==> Stopping the stock coturn systemd unit..."
    systemctl stop coturn
    systemctl disable coturn 2>/dev/null || true
fi

echo "==> Configuring ufw (allow SSH first to avoid lockout)..."
ufw allow OpenSSH >/dev/null
ufw allow 3478/udp >/dev/null
ufw allow 3479/udp >/dev/null
if ! ufw status | grep -q "Status: active"; then
    echo "y" | ufw enable >/dev/null
fi

echo "==> Starting coturn in tmux session '$TMUX_SESSION'..."
# Kill any prior instance of our tmux session and any stray turnserver
tmux kill-session -t "$TMUX_SESSION" 2>/dev/null || true
pkill -f 'turnserver -c '"$CONF_FILE" 2>/dev/null || true
sleep 1
: > "$LOG_FILE"
tmux new-session -d -s "$TMUX_SESSION" "turnserver -c $CONF_FILE 2>&1 | tee -a $LOG_FILE"

# Wait up to 5s for coturn to print the startup banner
for i in {1..10}; do
    if grep -q "Total General servers:" "$LOG_FILE" 2>/dev/null; then
        break
    fi
    sleep 0.5
done

echo "==> Verifying coturn config — grepping log for misconfig signals..."
# Wording varies across coturn versions, so match the substrings that are
# stable across 4.5/4.6/4.10:
#   - "RFC5780 disabled" only appears on 4.10+ (default flipped to OFF) when
#     rfc5780 directive isn't in the conf
#   - "only one IP" appears on every coturn version when fewer than 2 distinct
#     routable IPs are configured (4.6: "cannot support ... functionality
#     because only one IP address is provided"; 4.10: "STUN CHANGE_REQUEST
#     not supported: only one IP address is provided")
FAILED=0
if grep -q "RFC5780 disabled" "$LOG_FILE"; then
    echo "    FAIL: 'RFC5780 disabled' in log — rfc5780 directive missing or ignored" >&2
    FAILED=1
fi
if grep -qi "only one IP" "$LOG_FILE"; then
    echo "    FAIL: 'only one IP address is provided' in log — coturn needs 2 distinct routable IPs to honor CHANGE_REQUEST" >&2
    FAILED=1
fi

if [[ $FAILED -eq 1 ]]; then
    echo
    echo "Config did NOT pass §4.4 readiness checks. Last 30 log lines:"
    tail -30 "$LOG_FILE" >&2
    exit 1
fi

echo "    OK — no 'RFC5780 disabled' or 'STUN CHANGE_REQUEST not supported' in log"
echo

cat <<EOF
==============================================================================
coturn ready. From your laptop (and at least one other network):

    natcheck --server $PUBLIC_IP:3478 --json --timeout 5s

Expected: filtering.behavior is one of {endpoint-independent,
address-dependent, address-and-port-dependent}, NOT "untested".

Logs:        tail -f $LOG_FILE
Attach tmux: tmux attach -t $TMUX_SESSION    (detach: Ctrl-b d)
Stop:        tmux kill-session -t $TMUX_SESSION

DESTROY THE DROPLET WHEN DONE. poweroff is not enough — billing continues
until destroy from the cloud dashboard.
==============================================================================
EOF
